import type { CoursePlan } from "./types";

export const COURSE_PLANS: CoursePlan[] = [
  {
    id: "demo",
    name: "DEMO",
    tag: "Program 01 · Beginner",
    duration: "5 Days · Online & Offline",
    price: 0,
    originalPrice: 5000,
    discount: "100% OFF",
    features: [
      "How financial markets actually work",
      "Candlestick reading without memorizing patterns",
      "Support & resistance done right",
      "Trend identification and market context",
      "Introduction to Fundamental Analysis",
      "Structured trade planning basics",
    ],
  },
  {
    id: "advance",
    name: "ADVANCE",
    tag: "Program 02 · Advanced · Most Popular",
    duration: "4 Weeks · Online & Offline",
    price: 14999,
    originalPrice: 29999,
    discount: "50% OFF",
    features: [
      "Advanced price action and order flow",
      "Market structure — highs, lows, and shifts",
      "Breakout models and entry frameworks",
      "Multi-timeframe analysis and confluence",
      "Build your own personal trading system",
      "Live trade analysis and review sessions",
    ],
    featured: true,
  },
  {
    id: "advance-live",
    name: "ADVANCE + LIVE",
    tag: "Program 03 · Mentorship",
    duration: "6 Weeks · 12 Seats/Batch",
    price: 19999,
    originalPrice: 39999,
    discount: "50% OFF",
    features: [
      "All Advanced Program content included",
      "Live trade management and position handling",
      "Weekly live trade review sessions",
      "Personal trade journal feedback",
      "Real-time market analysis guidance",
      "Trading psychology and mindset coaching",
    ],
  },
];

export const TICKER_ITEMS = [
  "PRICE ACTION", "MARKET STRUCTURE",
  "ORDER FLOW", "SUPPORT & RESISTANCE", "INSTITUTIONAL THINKING",
  "RISK MANAGEMENT", "TRADING PSYCHOLOGY", "CANDLESTICK ANALYSIS", "FINVISION RAIPUR",
];

export const CANDLE_DATA = [
  { h: 100, b: 70, t: 30, up: true },
  { h: 90, b: 60, t: 25, up: false },
  { h: 95, b: 65, t: 20, up: true },
  { h: 80, b: 55, t: 22, up: false },
  { h: 85, b: 58, t: 18, up: false },
  { h: 70, b: 48, t: 15, up: false },
  { h: 75, b: 50, t: 12, up: false },
  { h: 60, b: 40, t: 10, up: false },
  { h: 65, b: 42, t: 8, up: false },
  { h: 50, b: 33, t: 7, up: false },
  { h: 55, b: 36, t: 5, up: false },
  { h: 40, b: 26, t: 4, up: false },
];

export const FAQS = [
  { q: "Is this for complete beginners?", a: "Yes. Our Foundation program starts from absolute zero — how markets work, why price moves, how to read a chart. No prior experience needed." },
  { q: "Do you provide tips or signals?", a: "No. We focus entirely on building your own decision-making ability. We teach you to not need tips or signals — that's the whole point." },
  { q: "Online or offline — which is better?", a: "Both are equally structured. Offline at Raipur gives you direct mentor access during live market hours. Online gives you flexibility. Choose based on your location and schedule." },
  { q: "What is the fee for each program?", a: "Foundation: ₹8,000 · Advanced: ₹15,000 · Mentorship: ₹25,000. EMI is available on request. WhatsApp us for the latest batch-specific details." },
  { q: "How long does it take to learn?", a: "Programs run 8–12 weeks. Most students report clarity in their thinking within 3–4 weeks. Real skill takes 3–6 months of consistent practice after the program." },
  { q: "What happens after I submit the form?", a: "Our team will WhatsApp you within a few hours to understand your background and guide you to the right program. No pressure — just a conversation." },
];

export const POSTS = [
  {
    id: "what-is-forex-trading",
    cat: "Beginner Trading",
    title: "",
    subtitle: "",
    excerpt: "Over the last few years, forex trading has become one of the most talked-about ways of online trading in India. Many students, working professionals, and business owners are now exploring the forex market to understand how currency trading works and whether it can become a source of income.",
    read: "5 min",
    author: "Akshay Sir",
    date: "Apr 12, 2026",
    image: "/blog-forex-trading.jpg",
    body: [
      "Over the last few years, forex trading has become one of the most talked-about ways of online trading in India. Many students, working professionals, and business owners are now exploring the forex market to understand how currency trading works and whether it can become a source of income.",
      "In simple language, forex trading means exchanging one currency for another to earn profit from price movement. Traders buy currencies at one price and try to sell them later at a better price. The forex market is the biggest financial market in the world because currencies are traded globally every second. Banks, companies, governments, and retail traders all participate in this market daily.",
      "## Understanding the Forex Market",
      "The word ‘Forex’ comes from ‘Foreign Exchange.’ It refers to the exchange of currencies between countries. Currencies are traded in pairs such as EUR/USD, GBP/USD, USD/JPY, and USD/INR — meaning one currency is compared against another. If EUR/USD moves upward, the Euro is becoming stronger compared to the US Dollar, and this movement creates trading opportunities.",
      "## How Forex Trading Works",
      "A trader predicts whether a currency pair will go up or down. If the trader believes the price will rise, they place a buy trade. If they believe the price will fall, they place a sell trade. The difference between the buying and selling price becomes the profit or loss. For example, if USD/INR is at 83.00 and you expect the dollar to strengthen, you buy the pair. If it rises to 83.50, you close the trade in profit.",
      "## Why is Forex Trading Popular?",
      "The forex market attracts millions of traders for several reasons. It runs almost 24 hours a day during weekdays, giving flexibility to students, working professionals, and part-time traders. The market has extremely high trading volume, so trades execute quickly and price manipulation is lower compared to smaller markets. Many beginners are also attracted by the relatively smaller capital needed to start — but proper learning should always come before investing real money.",
      "## Forex Trading Basics Every Beginner Should Learn",
      "Currency pairs are at the heart of every forex trade. The base currency and the quote currency make up each pair, and understanding how they move relative to each other is the first step. A pip is the smallest unit of price movement, while lot size refers to the quantity of currency being traded. Beginners usually start with micro or mini lots to reduce risk exposure.",
      "Leverage allows traders to control larger positions using smaller capital. While this can amplify profits, it equally amplifies losses — and beginners who misuse leverage often wipe accounts before learning anything. Use leverage carefully and always within a defined risk framework.",
      "## How Beginners Can Start Forex Trading",
      "Start by building foundational knowledge — market trends, risk management, trading psychology, and reading charts. Then practice on a demo account to understand the trading platform and test strategies without risking real money. Once comfortable, develop a trading strategy. Successful traders do not trade randomly. Common beginner strategies include trend trading, breakout trading, and support-resistance based entries.",
      "The most critical step is focusing on risk management. Never risk all your capital in a single trade, always use a stop loss, and avoid emotional decisions. Poor risk management is the single biggest reason traders fail — not a lack of profitable setups.",
      "## Is Forex Trading Legal in India?",
      "Forex trading is legal in India when done according to RBI and SEBI guidelines through authorised brokers and approved currency pairs. Traders should always avoid unregulated platforms and unknown brokers. Learning the legal framework of currency trading is an important step before committing real capital.",
      "## Is Forex Trading Profitable?",
      "Forex trading has the potential to become profitable, but it is not a guaranteed income source. Many people enter expecting fast money. In reality, trading requires skill, discipline, practice, and emotional control. Experienced traders spend years refining their strategies and deepening their understanding of market behaviour. Success in trading comes from consistency and structured learning — not luck.",
      "Common beginner mistakes to avoid: trading without knowledge, overusing leverage, making emotional decisions, trading without a plan, and ignoring risk management. Each of these is avoidable with proper education and honest self-assessment.",
      "## Why Forex Education Matters",
      "The forex market is highly competitive, and proper education can save beginners from expensive mistakes. Learning from experienced mentors and studying real market conditions builds both confidence and decision-making ability. A structured forex trading course covers technical analysis, trading psychology, risk management, and live market exposure. Rather than following random signals online, focus on building knowledge that will serve you for years — that is the foundation every successful trader is built on.",
    ],
  },
  {
    id: "trader-vs-gambler",
    cat: "Trading Psychology",
    title: "TRADER VS GAMBLER (The Truth Nobody Tells You)",
    subtitle: "Why most people lose money in the markets — and how to make sure you are not one of them.",
    metaTitle: "Trader vs Gambler: The Truth Nobody Tells You | FINVISION",
    metaDescription: "Most traders lose money because they trade like gamblers. Learn the real difference between a professional trader and a gambler in this detailed FINVISION guide.",
    excerpt: "Most people think trading and gambling are the same. They are not. At a glance they may seem similar — both involve money, risk, and making decisions under pressure. But dig deeper and the difference becomes clear. One is built on randomness. The other is built on a system.",
    read: "6 min",
    author: "Goutam Soni",
    date: "May 22, 2026",
    image: "",
    body: [
      "Most people think trading and gambling are the same. They are not. At a glance they may seem similar — both involve money, risk, and making decisions under pressure. But dig deeper and the difference becomes clear. One is built on randomness. The other is built on a system.",
      "This is the truth nobody tells beginners when they first open a trading account. And it is exactly why most people lose money within their first six months.",
      "## A Gambler Relies on Luck",
      "A gambler enters a bet hoping for a favourable outcome. They might use streaks, gut feelings, past results, or pure emotion to decide when and how much to risk. There is no repeatable framework. There is no defined process. Every decision is shaped by hope — not by logic.",
      "In trading, this looks like jumping into a trade because a stock is moving fast. It looks like doubling down on a losing position because 'it has to come back.' It looks like exiting too early because the profit felt good, or holding too long because the loss felt unacceptable. These are not trading decisions. They are gambling decisions dressed in trading language.",
      "## A Trader Relies on Discipline",
      "A professional trader operates completely differently. Before entering any trade, they have already answered: What is my entry point and why? Where is my stop loss? What is the reward I am targeting? How much of my account am I risking on this single trade?",
      "These questions are not asked in the moment. They are answered before the market opens. A trader follows a pre-defined system — and more importantly, they follow it even when emotions say otherwise. The plan does not change because the market feels exciting or frightening.",
      "## The Real Difference Is the Mindset",
      "A gambler thinks in terms of individual outcomes. Did I win this trade? Did I lose that one? Every result feels personal.",
      "A trader thinks in terms of probabilities over a series of trades. A single loss is not a failure — it is an expected part of running a strategy. A single win is not success — it is one data point in an ongoing process. The trader's goal is not to win every trade. The goal is to make sure that, over 50 or 100 trades, the system is profitable.",
      "This shift in perspective is what separates consistent traders from people who blow their accounts.",
      "## Most Retail Traders Trade Like Gamblers",
      "This is not an insult — it is an observation. Most beginners have never been taught to trade with structure. They have watched YouTube videos, followed tips in Telegram groups, copied trades from social media, and made decisions based on trending news. None of these are trading approaches. They are gambling approaches with extra steps.",
      "The moment you stop asking 'what will the market do next?' and start asking 'what is my process for every situation?' — that is the moment you cross from gambler to trader.",
      "## What Professional Trading Actually Looks Like",
      "A professional trader's day is mostly waiting. They have a watchlist. They have defined conditions under which they will enter a trade. They sit and wait. If the conditions are met, they take the trade. If not, they do nothing. There is no urgency. There is no FOMO. There is no excitement from the volatility — only execution of the plan.",
      "Their risk per trade is fixed — usually between 0.5% and 2% of total capital. They never risk more because a setup 'looks really good.' Every trade, without exception, uses a stop loss.",
      "## It Is the Mindset Behind Every Decision",
      "Trading is not about which indicator you use or which timeframe you prefer. It is about the quality of your decision-making under pressure. Two traders can see the same chart, use the same strategy, and get completely different results — because one follows the plan and the other lets emotions take over.",
      "If you want to trade seriously, the first thing to fix is not your strategy. It is your relationship with money, risk, and uncertainty. That is where real trading education begins.",
      "— FINVISION",
    ],
  },
];

export const CATS = ["All", "Beginner Trading", "Price Action", "Trading Psychology", "Market Analysis"];
